### ISSUE TITLE
Screen freeze in latest Monterey builds with external monitor

### ISSUE THREAD

**Issue by glouel** [AerialScreensaver/Aerial#42]
Hi there, I wanted to see if this is still being researched.

I seem to have just started having this issue with 12.4/12.5 of Mac Monterey.   I did go to the latest beta 1.2.2 (3.1.0beta3) and that didn't help.

For me, I have an external monitor and my Mac open (unclamshelled).   The lockup happens between 12-24 hours.   The only screen that ever locks up is the main Mac.   The external 34" monitor never has the issue.  In fact after the main Mac lockups, I have let the external monitor go for another 12+ hours with no issues.  Both are using different screensavers if that's helpful information.

Closing the laptop and reopening it fixes it, but it will eventually lockup again (usually during a conference call when I am using both screens).

Let me know if there are debug logs or something I can attach.  I am using a Intel MacBookPro16,2 32GB RAM.

Thanks!

_Originally posted by @TheRealChannelD in https://github.com/AerialScreensaver/AerialCompanion/issues/31#issuecomment-1215416450_

**Comment by glouel** [comment]
@TheRealChannelD

As far as I know there were no issue anymore, but I've had sparse reports of issues with latest Monterey beta. 

Let's try to clarify a few things: 

> The lockup happens between 12-24 hours

So you have Aerial running for 12-24 hours ? Your screen is set up to never go to sleep, just to be clear ?

> The only screen that ever locks up is the main Mac. 

So you have your Mac + external screen. Video keeps playing on your external screen, but does NOT on your Mac screen, correct ? 

Video is frozen... but you can still unlock everything correctly ?

> Both are using different screensavers if that's helpful information.

You mean both are running Aerial, but screens are setup as independant videos ? Or literally separate screensavers ??

Thanks

**Comment by TheRealChannelD** [comment]
Thanks for the response back.  Hope this helps for clarity

> @TheRealChannelD
> 
> As far as I know there were no issue anymore, but I've had sparse reports of issues with latest Monterey beta.
> 
> Let's try to clarify a few things:
> 
> > The lockup happens between 12-24 hours

> 
> So you have Aerial running for 12-24 hours ? Your screen is set up to never go to sleep, just to be clear ?

Yes, that is correct.  I have show screen saver after 20 mins and they never go to sleep.  The guess of 12-24 hours is that if I reboot, or clamshell the laptop in am (like 8).  It will be locked up by nighttime.  It might happen sooner than 12 hours, but it doesn't happen until after many transitions.

> 
> > The only screen that ever locks up is the main Mac.
> 
> So you have your Mac + external screen. Video keeps playing on your external screen, but does NOT on your Mac screen, correct ?

Correct.

> 
> Video is frozen... but you can still unlock everything correctly ?

The screensaver is frozen.  If I try to mouse over to Mac, I don't see the cursor and I can't drag a screen over there.   When I close and open the laptop, the screensaver stops on both and I can reuse the laptop screen again without having to power cycle it.  

> 
> > Both are using different screensavers if that's helpful information.
> 
> You mean both are running Aerial, but screens are setup as independant videos ? Or literally separate screensavers ??

Correct.  I just wanted different pictures on both.

> 
> Thanks

Also, I did just notice the cache being used was 13.5 GB.  Since I have a 4TB SSD, I increase it to unlimited.

**Comment by glouel** [comment]
> Thanks for the response back. Hope this helps for clarity
> 
> > @TheRealChannelD
> > As far as I know there were no issue anymore, but I've had sparse reports of issues with latest Monterey beta.
> > Let's try to clarify a few things:
> > > The lockup happens between 12-24 hours
> 
> > So you have Aerial running for 12-24 hours ? Your screen is set up to never go to sleep, just to be clear ?
> 
> Yes, that is correct. I have show screen saver after 20 mins and they never go to sleep. The guess of 12-24 hours is that if I reboot, or clamshell the laptop in am (like 8). It will be locked up by nighttime. It might happen sooner than 12 hours, but it doesn't happen until after many transitions.

So again to be clear, you reboot in the morning, your screen saver comes up, you DON'T use your mac at all during the day, Aerial plays CONTINUOUSLY and then at some point, video freezes on your Mac screen but keeps playing on your secondary screen. 

We're NOT talking about doing something with your mac, having it go to screensaver after 20 mins, using it again, etc etc ?

> > Video is frozen... but you can still unlock everything correctly ?
> 
> The screensaver is frozen. If I try to mouse over to Mac, I don't see the cursor and I can't drag a screen over there. When I close and open the laptop, the screensaver stops on both and I can reuse the laptop screen again without having to power cycle it.

Ok this I don't quite get. The video is still running on your second screen if I understood ? If you press a keyboard key, does the Mac not wake up ? The video just keeps playing on that second screen ? Or the second screen wakes up, but not your Mac screen ?

> > You mean both are running Aerial, but screens are setup as independant videos ? Or literally separate screensavers ??
> 
> Correct. I just wanted different pictures on both.

Makes sense.

Thanks for the info, I think I maybe get it a bit more clearly, but this is weird and new.

**Comment by TheRealChannelD** [comment]
> > Thanks for the response back. Hope this helps for clarity
> > > @TheRealChannelD
> > > As far as I know there were no issue anymore, but I've had sparse reports of issues with latest Monterey beta.
> > > Let's try to clarify a few things:
> > > > The lockup happens between 12-24 hours
> > 
> > 
> > > So you have Aerial running for 12-24 hours ? Your screen is set up to never go to sleep, just to be clear ?
> > 
> > 
> > Yes, that is correct. I have show screen saver after 20 mins and they never go to sleep. The guess of 12-24 hours is that if I reboot, or clamshell the laptop in am (like 8). It will be locked up by nighttime. It might happen sooner than 12 hours, but it doesn't happen until after many transitions.
> 
> So again to be clear, you reboot in the morning, your screen saver comes up, you DON'T use your mac at all during the day, Aerial plays CONTINUOUSLY and then at some point, video freezes on your Mac screen but keeps playing on your secondary screen.
> 
> We're NOT talking about doing something with your mac, having it go to screensaver after 20 mins, using it again, etc etc ?

I will clarify.  After the lockup I have tried rebooting or not rebooting and just clamshelling.   M-F I tend to do stuff with my Mac at least once an hour, I rarely see it lock up then.  On weekends, I come to the computer and its like this in the morning (after sitting 8-12 hours overnight).   I check email and don't mess with it all day, come back after dinner and its in this state.    I have seen it do this through the workday, but less frequently.   So in transparency, 12-24 hours was probably wrong.  It does this after some time, but not after the first transition.  I usually come back to find it hung.  If you want (since I am displaying the time and it hangs with that) I can give you an exact timeframe the next time I see it.

> > > Video is frozen... but you can still unlock everything correctly ?
> > 
> > 
> > The screensaver is frozen. If I try to mouse over to Mac, I don't see the cursor and I can't drag a screen over there. When I close and open the laptop, the screensaver stops on both and I can reuse the laptop screen again without having to power cycle it.
> 
> Ok this I don't quite get. The video is still running on your second screen if I understood ? If you press a keyboard key, does the Mac not wake up ? The video just keeps playing on that second screen ? Or the second screen wakes up, but not your Mac screen ?

Yes, pressing a key doesn't wake that screen up.  The frozen part means the screensaver and time look frozen.  I originally thought interrupts were disabled on that monitor, but I think it's more that the screensaver overtakes the topmost screen so it just looks like that.  It took me awhile of not rebooting to realize just clamshelling it for a second and opening back would get it unstuck.   

> 
> > > You mean both are running Aerial, but screens are setup as independant videos ? Or literally separate screensavers ??
> > 
> > 
> > Correct. I just wanted different pictures on both.
> 
> Makes sense.
> 
> Thanks for the info, I think I maybe get it a bit more clearly, but this is weird and new.

I am happy to pass over  anything else you need.  Thanks for looking into it.  

Also, I finished working at my computer at 14:23:10 today.   I came back at 19:57:20 and the Mac was stuck on 17:51:40, so I guess it froze about 90 mins later.    I will let it go and see how long it takes to happen again.

**Comment by TheRealChannelD** [comment]
Hi there, I tried a few things late last night into overnight.

1) I didn't remove my external cable, but I changed my external monitor input to my PC.  This forces the Mac to just believe it has the one desktop.

2) I started and monitored the screensavers.  Each time I manually started it and noted the time started and time it froze.  I didn't reboot, all I did was clamshell the Mac for a second to clear it and open it back up and restart.

17:51:40 manually started
19:57:20 frozen

20:03:28 manually started
20:51:07 frozen

21:21:19 manually started
7:45:09 still running after 10-11 hours, woke Mac to do some email

So as you can see, it looks like I could have an issue in under an hour or it run all night.   Random and odd.

I do have the System Info file if that would help.

> > > Thanks for the response back. Hope this helps for clarity
> > > > @TheRealChannelD
> > > > As far as I know there 
[MacBook Pro.spx.zip](https://github.com/AerialScreensaver/AerialCompanion/files/9350847/MacBook.Pro.spx.zip)
[MacBook Pro.spx.zip](https://github.com/AerialScreensaver/AerialCompanion/files/9350850/MacBook.Pro.spx.zip)
were no issue anym
[MacBook Pro.spx.zip](https://github.com/AerialScreensaver/AerialCompanion/files/9350873/MacBook.Pro.spx.zip)
ore, but I've had sparse reports of issues with latest Monterey beta.
> > > > Let's try to clarify a few things:
> > > > > The lockup happens between 12-24 hours
> > > 
> > > 
> > > > So you have Aerial running for 12-24 hours ? Your screen is set up to never go to sleep, just to be clear ?
> > > 
> > > 
> > > Yes, that is correct. I have show screen saver after 20 mins and they never go to sleep. The guess of 12-24 hours is that if I reboot, or clamshell the laptop in am (like 8). It will be locked up by nighttime. It might happen sooner than 12 hours, but it doesn't happen until after many transitions.
> > 
> > 
> > So again to be clear, you reboot in the morning, your screen saver comes up, you DON'T use your mac at all during the day, Aerial plays CONTINUOUSLY and then at some point, video freezes on your Mac screen but keeps playing on your secondary screen.
> > We're NOT talking about doing something with your mac, having it go to screensaver after 20 mins, using it again, etc etc ?
> 
> I will clarify. After the lockup I have tried rebooting or not rebooting and just clamshelling. M-F I tend to do stuff with my Mac at least once an hour, I rarely see it lock up then. On weekends, I come to the computer and its like this in the morning (after sitting 8-12 hours overnight). I check email and don't mess with it all day, come back after dinner and its in this state. I have seen it do this through the workday, but less frequently. So in transparency, 12-24 hours was probably wrong. It does this after some time, but not after the first transition. I usually come back to find it hung. If you want (since I am displaying the time and it hangs with that) I can give you an exact timeframe the next time I see it.
> 
> > > > Video is frozen... but you can still unlock everything correctly ?
> > > 
> > > 
> > > The screensaver is frozen. If I try to mouse over to Mac, I don't see the cursor and I can't drag a screen over there. When I close and open the laptop, the screensaver stops on both and I can reuse the laptop screen again without having to power cycle it.
> > 
> > 
> > Ok this I don't quite get. The video is still running on your second screen if I understood ? If you press a keyboard key, does the Mac not wake up ? The video just keeps playing on that second screen ? Or the second screen wakes up, but not your Mac screen ?
> 
> Yes, pressing a key doesn't wake that screen up. The frozen part means the screensaver and time look frozen. I originally thought interrupts were disabled on that monitor, but I think it's more that the screensaver overtakes the topmost screen so it just looks like that. It took me awhile of not rebooting to realize just clamshelling it for a second and opening back would get it unstuck.
> 
> > > > You mean both are running Aerial, but screens are setup as independant videos ? Or literally separate screensavers ??
> > > 
> > > 
> > > Correct. I just wanted different pictures on both.
> > 
> > 
> > Makes sense.
> > Thanks for the info, I think I maybe get it a bit more clearly, but this is weird and new.
> 
> I am happy to pass over anything else you need. Thanks for looking into it.
> 
> Also, I finished working at my computer at 14:23:10 today. I came back at 19:57:20 and the Mac was stuck on 17:51:40, so I guess it froze about 90 mins later. I will let it go and see how long it takes to happen again.

**Comment by glouel** [comment]
> Yes, pressing a key doesn't wake that screen up. 

Sorry to insist but this is critical and I want to be 100% sure I get it : does the other screen wakes up and show your mac desktop when you press a key, and just the Mac screen is stuck ?

> I didn't remove my external cable, but I changed my external monitor input to my PC. This forces the Mac to just believe it has the one desktop.

FYI I run the exact same setup with a cheap display port switch :) 

So in that scenario, only your mac internal screen (the one that gets stuck). 

> I started and monitored the screensavers. Each time I manually started it and noted the time started and time it froze. I didn't reboot, all I did was clamshell the Mac for a second to clear it and open it back up and restart.

> 17:51:40 manually started
> 19:57:20 frozen

> 20:03:28 manually started
> 20:51:07 frozen

> 21:21:19 manually started
> 7:45:09 still running after 10-11 hours, woke Mac to do some email

> So as you can see, it looks like I could have an issue in under an hour or it run all night. Random and odd.

> I do have the System Info file if that would help.

So first something nice would be, if you can go to Aerial's settings, Advanced, scroll down a bit, enable logs. This will enable Aerial's internal logging. Feel free to send me your log with the times of your experiments, just one should do. I should have given you those instructions yesterday sorry about that!

From then on maybe we can try and understand this a bit better, but long story short, the screensaver isn't in charge of stopping itself, waking up your mac, etc, this is all macOS, the screensaver is very passive in all this so it's very likely a macOS bug but hopefully we can narrow it down to file a feedback.

**Comment by TheRealChannelD** [comment]
> > Yes, pressing a key doesn't wake that screen up.
> 
> Sorry to insist but this is critical and I want to be 100% sure I get it : does the other screen wakes up and show your mac desktop when you press a key, and just the Mac screen is stuck ?

Yes, the external 34" widescreen always wakes up 100% of the time and never has an issue.   

> 
> > I didn't remove my external cable, but I changed my external monitor input to my PC. This forces the Mac to just believe it has the one desktop.
> 
> FYI I run the exact same setup with a cheap display port switch :)
> 
> So in that scenario, only your mac internal screen (the one that gets stuck).

Yes, I tried this hoping to see if the behavior changed.  Only the Mac was running the screensaver overnight.    It still got stuck.

> 
> > I started and monitored the screensavers. Each time I manually started it and noted the time started and time it froze. I didn't reboot, all I did was clamshell the Mac for a second to clear it and open it back up and restart.
> 
> > 17:51:40 manually started
> > 19:57:20 frozen
> 
> > 20:03:28 manually started
> > 20:51:07 frozen
> 
> > 21:21:19 manually started
> > 7:45:09 still running after 10-11 hours, woke Mac to do some email
> 
> > So as you can see, it looks like I could have an issue in under an hour or it run all night. Random and odd.
> 
> > I do have the System Info file if that would help.
> 
> So first something nice would be, if you can go to Aerial's settings, Advanced, scroll down a bit, enable logs. This will enable Aerial's internal logging. Feel free to send me your log with the times of your experiments, just one should do. I should have given you those instructions yesterday sorry about that!
> 
> From then on maybe we can try and understand this a bit better, but long story short, the screensaver isn't in charge of stopping itself, waking up your mac, etc, this is all macOS, the screensaver is very passive in all this so it's very likely a macOS bug but hopefully we can narrow it down to file a feedback.

Ok, I enabled logs.  I have some things to do on my Mac today, but as soon as I see this behavior will note it and send the log over.

**Comment by TheRealChannelD** [comment]
Hi there, so I don't think this is helpful, but after enable debug logging the freeze stopped.  I waited over 24 hours.   I disabled the debugging and got two freezes in about 4 hours.  I then re-enabled it and haven't seen a freeze in over 24 hours.  Odd huh?  I bet you didn't expect debugging to change the stack enough to hide it, but hey on the positive note I guess I have a fix.  ;-)  So I guess it's like how when you take your car to the shop and when the mechanic checks it, it works fine.  (sigh)  I'll leave debugging on to see if it ever happens.

**Comment by glouel** [comment]
Now that's a weird one for sure, thanks for the update @TheRealChannelD 

One reason I can see is that logging causes writes to your internal mac SSDs, and maybe that's sufficient to keep it awoken and avoid whatever weird sleep status it got itself into ? I say keep debug mode enabled, it's always good to have logs in case something else break ;)

**Comment by TheRealChannelD** [comment]
I did see the screen freeze last night after weeks of no issues.   The screen time says '23:25:20'.  My full log was 500MB so I just trimmed it down to the last month and uploading that.
[AerialLog.txt.zip](https://github.com/AerialScreensaver/AerialCompanion/files/9496852/AerialLog.txt.zip)

**Comment by glouel** [comment]
Hey @TheRealChannelD 

Sorry it took me so long to answer, but the 500 MB thing needed definitive correction and I could only take care of it this week end. 

So I finally did with 3.1.3 which I just released. It will cap the log size to 1 MB.

I would suggest you try again with that version, and make sure that the debug logging is still enabled. It's possible that the file being so large had an effect on the bug returning, considering it seems the core issue is the system drive going to sleep. Please try 3.1.3 when you can and let me know if it fixes things.

**Comment by dserodio** [comment]
I'm experiencing a similar problem, but I did not troubleshoot it yet. I use 2 external monitors along with the built-in display, with different Aerial screensavers on each of them and it's very common for the screensaver to freeze on the built-in display. Running macOS Monterrey 12.5.1 and Aerial Companion 1.2.2. After reading this issue I just updated Aerial from 3.1.2 to 3.1.3 and enabled debug logging hoping that it will fix the problem.

**Comment by TheRealChannelD** [comment]
I can report so far I do see the log size is down.   I haven't seen any issues yet.

I do notice both the release and beta for me say 3.1.3.  I stayed on the beta channel, but maybe you decided to take the fix live.  Was curious about that.

**Comment by glouel** [comment]
Yep when there's no beta, it shows the latest release as the most recent beta, it's a bit weird but it's to make sure that if you are on the beta track, you still get the latest release if that's the latest ;) 

I had a couple of other reports that were similar to yours, so far the debug log trick seems to work somehow... let's hope it sticks !

**Comment by TheRealChannelD** [comment]
After several days of no issues, I did have a problem this evening around an hour ago (19:11:03 was on the screen).  Attaching the log in hopes it captured something.   As far as I know, none of my software has changed.

PS I sent coffee money because I'm sure I've kept you up lately.  Cheers!

[AerialLog 19.11.03 9-20-22.txt.zip](https://github.com/AerialScreensaver/AerialCompanion/files/9611920/AerialLog.19.11.03.9-20-22.txt.zip)

**Comment by glouel** [comment]
Damn it, I thought we had it ! I'll have a look at your log tomorrow and let you know !

And thanks for the coffee, it's definitely not required but very much appreciated !

**Comment by TheRealChannelD** [comment]
Hey there... didn't want to be pushy, but I saw it happen again and wonder if you discovered anything more.  Unfortunately it was right about the time Hurricane Ian hit and as luck would have it, the log did get overwritten since its cyclical logging now.   Sorry about that.

**Comment by TheRealChannelD** [comment]
Hey there.   Not sure if you are making any more tweaks.   Did want you to know I still see it from time to time.

**Comment by glouel** [comment]
Hey, sorry, haven't found anything yet. Please let me know if you still have more details about this. I do have a workaround possibly with the next version of Companion though, I'll keep you posted soon.

**Comment by TheRealChannelD** [comment]
When it happens I can send another log if you think that will help.   I will say you mentioned something before that might be important.   When I am doing TimeMachine backup, the screen lockups seem to happen more frequently.    The backups finish more though so it doesn't affect that.

**Comment by TheRealChannelD** [comment]
I can definitely confirm it happens more frequently with a disk plugged in a regular Time Machine backups if helpful.   It continues to be the primary laptop display.  The screensaver on the secondary monitor never freezes which I continue to think is a little odd.  Could it have something to do with that?

**Comment by glouel** [comment]
Hey there, couple of things :
- how's your Time Machine disk plugged (USB-A/USB-C, directly to your mac or behind a hub)

Reason I'm asking: I've had tons of issues on my Mac Studio with my Time Machine SSD when connected to USB-C, it would randomly disconnect. Somehow, switching it to USB-A solved it all. USB can be weird and some USB issues can lead to unpredictable stuff so, some checking around that could help. 

- and is it a spinning drie or a SSD ?

Spinning hard drive have a hard tendency to go to sleep on their own on some usb enclosures so, that could be something too.

**Comment by TheRealChannelD** [comment]
Thanks for the note back.  The drives I use are WD My Passport Drives (a 4 platter spindle drive, USB C 3.2 Gen1) plugged directly into one of the 4 USB C ports on my MacBookPro16,2.  Never use a hub with USB-A (but understand that may change the device timing).   If it helps, I have all power management (including Power Nap, put disks to sleep, etc. turned off because it stays connected in one play always).    

Just curious, would it make any sense to drop some USB port debugging stuff into the beta code to see if something wonky is going on during this situation?  If so, I can load and send logs again.   PS My external monitor that never freezes up is connected to a 2nd USB C port on laptop (if helpful information).

Thanks again!  Cheers!

**Comment by glouel** [comment]
The problem is, this is completely out of my control as it's very likely a bug somewhere in macOS that causes the issue, and there's little I can gather from Aerial as we are heavily sandboxed. 

I think the best you could do to narrow it down is maybe capturing the Console output at the moment of a freeze, but that's probably not easy to do ? I guess if you leave Console.app running with the capture and manage to catch the moment of a freeze, you can wake it up and track down from here ? Does that make sense ?

**Comment by TheRealChannelD** [comment]
Yes, not sure how to setup console or capture just the moment.   I guess I was hopeful that the fact that the freeze happens on the main system, but not the remote monitor might be a clue.  I see in Sep @dserodio said he saw the same thing.  Not sure if it still affects him or not.

I am also running two different screensavers (different one on the main monitor than the laptop screen like I saw the other person was).  Not sure that matters, but not sure I saw in settings where to change that either.   ;-)

**Comment by dserodio** [comment]
I do not have external HD drives, but I do have a couple of USB peripherals like a keyboard, a Yubikey and an Ethernet adapter. I was using Aerial for a few weeks without problems but a couple of weeks before it froze again and my keyboard was getting a very strange delay when typing that was only solved by rebooting so I uninstalled Aerial for now.

When a new build comes out I'll be glad to try it again. I'd love to help troubleshooting but I'm not sure how.

**Comment by TheRealChannelD** [comment]
@glouel Just wanted to note that I did disconnect everything (except for my external monitor) and it is still happening.   I am running Ventura 13.4.1 now and it's actually gotten much worse in the last 2 weeks (twice a day).    I don't think there is really anything else you can do to help, but wanted to check.  The freeze was overnight @ 7-26-23 03:27:07.  I didn't see anything in the log, but all happy to try any other debugging, etc. you may have.

Cheers!
[AerialLog.txt](https://github.com/AerialScreensaver/AerialCompanion/files/12172168/AerialLog.txt)

**Comment by glouel** [comment]
Hey @TheRealChannelD 

I had a thorough look at your log and I really don't understand what is happening to you. From the log point of view, I see that you started your screen saver on two screens around 9pm.

This is your 34" : 

```
2023-07-25 21:01:32.790 : 🖼️ AVinit (.saver) (0.0, 0.0, 3440.0, 1440.0) p: false o: false
2023-07-25 21:01:32.792 : 🖼️ <AerialView: 0x7f7db0a23180> 
```

And your mac I guess on the left of it, the 34 being your "main" monitor is how I see it : 

```
2023-07-25 21:01:32.879 : 🖼️ AVinit (.saver) (-1680.0, 82.0, 1680.0, 1050.0) p: false o: false
2023-07-25 21:01:32.881 : 🖼️ <AerialView: 0x7f7daff14b80>
```

Note the AerialView that ends with "180" (34inch) and "b80" (mac), those are the two Aerial instances running and helps me track them independently in log. 

But both are running diligently through the night, until near 8 am.

Both keeps getting the notifications that the previous video played to its end : 

```
2023-07-26 07:52:07.469 : <AerialView: 0x7f7daff14b80> played did reach end
```

This is the last one from your mac, it still keeps running !

And it starts playing a new video too... 

```
2023-07-26 07:52:07.639 : 🖼️ <AerialView: 0x7f7daff14b80> observeValue Optional("readyForDisplay") true
2023-07-26 07:52:07.641 : 🖼️ start playback: (0.0, 0.0, 1680.0, 1050.0) (0.0, 0.0, 1680.0, 1050.0) rate: 1.0
```

And like a few seconds after that, you woke up your mac, here again, both get the events that macOS is stopping them : 

```
2023-07-26 07:52:51.264 : 🖼️ 📢📢📢 willStop
2023-07-26 07:52:51.266 : 🖼️ <AerialView: 0x7f7daff14b80> stopAnimation
2023-07-26 07:52:51.275 : 🖼️ 📢📢📢 willStop
2023-07-26 07:52:51.277 : 🖼️ <AerialView: 0x7f7db0a23180> stopAnimation
```

So from their point of view, they are running fine, so it's something else that freeze up the stack, is my best bet. 

I would suggest you update to 13.5 when you can @TheRealChannelD, as Apple fixed some pretty big core issues with multi monitor. I have no idea if that will fix your issue but it's worth a shot. Dual monitor setups still had occasional issues on 13.4 despite their partial fix, although your issue is really different so far. Yours could be something GPU overheating, some driver crashing, or something else weird, but it's likely an issue much higher up in macOS.

**Comment by glouel** [comment]
@TheRealChannelD 

Got an idea, please try opening "Console.app" on your mac then look at those two last sections on the left. Try to scroll around 03:27:07 and see if there's anything around that time. With a bit of luck if something hang, it will show up there in macOS logs. 

![Capture d’écran 2023-07-26 à 14 41 05](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/d2e1e9c7-e4ab-416a-afdf-edf6775277f2)

Check both the last sections (analysis data & system log) as it could be on either and let me know if you see something.

**Comment by TheRealChannelD** [comment]
Thanks @glouel.  This particular time I don't see anything in the system.log (attached)/

I poked around some more and do see a crashes over the last week in diagnostics reports that seem to map to similar times in legacyScreenSaver.  Is that yours or a culprit I should disable?

![Screenshot 2023-07-26 at 9 43 20 AM](https://github.com/AerialScreensaver/AerialCompanion/assets/66736186/5a0fc2f3-3b38-40cd-95cb-ed2336e0333e)

**Comment by glouel** [comment]
Ha ! 

legacyScreenSaver is part of macOS, it's the sandbox that runs all 3rd party and some 1st party screensavers from Apple. 

This is usually the cause of most bugs (the main multimonitor bugs are both linked to that). It's possible, because they changed it quite a bit in 13.5, that your bug could be related. If not I would suggest sending a feedback report to apple with the crash log so they can investigate on their end.

**Comment by glouel** [comment]
I'll close this as the v4 alphas no longer use legacyScreenSaver and handle external monitors better now.
