### ISSUE TITLE
MacOS Ventura shows Allowed Backgroud Parts with name Guillaume Louel

### ISSUE THREAD

**Issue by joostvdl** [AerialScreensaver/Aerial#47]
<img width="506" alt="Scherm­afbeelding 2022-10-26 om 22 40 41" src="https://user-images.githubusercontent.com/234896/198135340-1753b778-4804-489c-88f1-2ea3173bc082.png">

Mac OS:  Ventura 13.0
AerialCompanion: 1.2.2 

After isntalling AerialCompanion on Mac OS Ventura it shows a background part running with the name of Guillaume Louel.

This looks like a bug and should be Aerial Companion or something like that (see other applications). This looks if someone is hacking the system instead of a normal process...

**Comment by glouel** [comment]
Hey there, 

This is my name but indeed it looks terrible, for some reason this panel is displaying the name of the Company/Developer, and not the App name. 

This sounds like a bug in System Settings that nobody noticed or fixed yet. You can see Bitdefender SRL and Dragan Milic with the same issue. I'll try to dig a bit into this but it's very weird, all those have in common not to have an icon either, so this may be something.

In other parts of System Settings it does correctly display Aerial Companion, like in localisation services : 

<img width="569" alt="Capture d’écran 2022-10-26 à 23 03 55" src="https://user-images.githubusercontent.com/37544189/198137422-654c9d78-d9fa-43c1-a179-8b2bec551dec.png">

Thanks for the report I'll have a look but this looks like "one more thing" with System Settings 😩

**Comment by Feejus** [comment]
I can confirm I have the exact same issue. In fact, several times I get a notification in 13.1 MacOS Ventura that this app is running in the background.

**Comment by Feejus** [comment]
You can see the message i keep getting. 


![Issue](https://user-images.githubusercontent.com/36749383/208957120-9605bc70-141e-438f-a28c-a0799d568f5a.jpg)

**Comment by glouel** [comment]
Hey @Feejus 

I have the exact same thing here with VMware fusion at each macOS launch, I believe it's something that's either linked to the SDK used to compile, or just Ventura being extra painful about this. 

I'll try to investigate this next week, hopefully I can fix both issues.

**Comment by glouel** [comment]
@Feejus so I *think* this is fixed in my latest build, the background item notification. I no longer get it with this build : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

Can you confirm when you have a chance ? 

@joostvdl I'm still digging around the name thing, I spend pretty much all day on it yesterday to no avail, Keypass (https://github.com/keepassxreboot/keepassxc/issues/8818) and other software signed by independent developers seem to run into the same issue, while "team" certificates (used by most large companies) from Apple display the correct stuff.

Apple has introduced a new API in Ventura to add login items another way (which I'm not really feeling as a user, it keeps the login items inside the app which makes it harder to track who does what at first glance), I'll try to have another go at it when I can.

**Comment by Feejus** [comment]
> @Feejus so I _think_ this is fixed in my latest build, the background item notification. I no longer get it with this build : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip
> 
> Can you confirm when you have a chance ?
> 
> @joostvdl I'm still digging around the name thing, I spend pretty much all day on it yesterday to no avail, Keypass ([keepassxreboot/keepassxc#8818](https://github.com/keepassxreboot/keepassxc/issues/8818)) and other software signed by independent developers seem to run into the same issue, while "team" certificates (used by most large companies) from Apple display the correct stuff.
> 
> Apple has introduced a new API in Ventura to add login items another way (which I'm not really feeling as a user, it keeps the login items inside the app which makes it harder to track who does what at first glance), I'll try to have another go at it when I can.

Hi, 
I just downloaded it and ran it. I like the new design.  I am not sure if there is a specific steps i need to take or if i need to reboot my Mac but i just got these popup. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/36749383/210156487-d86f6d67-7223-4859-865e-f4d8f6a37666.png">


Quick Update:
After reboot i don't see the pop message anymore so far. I keep looking at this and keep you posted.

**Comment by Feejus** [comment]
I can confirm no more notifications popping up since the reboot. All seems to be working great so thank you.

**Comment by tm23** [comment]
I'm also on Ventura, and have updated to the latest release and still see the "Background Items Added" notifications all of the time

**Comment by glouel** [comment]
> I'm also on Ventura, and have updated to the latest release and still see the "Background Items Added" notifications all of the time

Are you using the companion beta or not ? https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

**Comment by tm23** [comment]
> > I'm also on Ventura, and have updated to the latest release and still see the "Background Items Added" notifications all of the time
> 
> Are you using the companion beta or not ? https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.0b3/Aerial.Companion.app.zip

Hello, yes, I have been running this beta version.

**Comment by glouel** [comment]
> Hello, yes, I have been running this beta version.

Thanks for confirming, can you try these steps ? https://github.com/AerialScreensaver/AerialCompanion/issues/51#issuecomment-1397265056

As mentioned, you should get one more prompt after doing this, then you should be ok.

**Comment by tm23** [comment]
> Thanks for confirming, can you try these steps ? [#51 (comment)](https://github.com/AerialScreensaver/AerialCompanion/issues/51#issuecomment-1397265056)
> 
> As mentioned, you should get one more prompt after doing this, then you should be ok.

That seems to have fixed things, thanks!

**Comment by shafti-code** [comment]
i had this issue today and even after i uninstalled the application i still have it as an option in the settings

<img width="465" height="54" alt="Image" src="https://github.com/user-attachments/assets/90623837-84d0-4af0-964a-6fb8db615b7c" />

system info
```console
OS: macOS 15.5 24F74 arm64
Host: MacBookPro18,3
Kernel: 24.5.0
Uptime: 12 days, 9 hours, 2 mins
Packages: 133 (brew)
Shell: zsh 5.9
Resolution: 1920x1080
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Dark)
Terminal: tmux
CPU: Apple M1 Pro
GPU: Apple M1 Pro
Memory: 4219MiB / 32768MiB
```

**Comment by glouel** [comment]
This is now fixed in the V4, I now use the new api for this provided by Apple and it shows Aerial in System Settings again in those sections. 

![Image](https://github.com/user-attachments/assets/3f558a98-093f-4a14-8732-342459e7cc4c)
